import { useState } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import { list, list2 } from '../assets/cards-list';
// import '../styles/globals.css';
import SearchFilter from '@/components/SearchFilter';
import Header from '@/components/Header';
import Cards from '@/components/Cards';
import HomeFooter from '@/components/HomeFooter';
import MobileFooter from '@/components/MobileFooter';
import ShowMapButton from '@/components/ShowMapButton';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ exploreData }) {
  console.log(exploreData)
  const [selectedFilter, setSelectedFilter] = useState(0);

  return (
    <div>
      <Head>
        <title>Hey Buddy!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <SearchFilter
        selectedFilter={selectedFilter}
        setSelectedFilter={setSelectedFilter}
      />
      {selectedFilter == 0 ? <Cards list={list} /> : <Cards list={list2} />}
      <ShowMapButton className='fixed top-12' />
      <MobileFooter />
      <HomeFooter className='fixed bottom-0' />

      {/* {exploreData?.map(item => (
        <h1>{item.title}</h1>
      ))} */}

    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/71XA').
    then(
      (res) => res.json()
    );

  return {
    props: {
      exploreData,
    },
  };
}
